import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import CryptoTable from "../components/crypto_table";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar></Navbar>
			<h1 className={styles.title}>
				Cryptocurrency Sentiment for Reddit
			</h1>

			<main className={styles.main}>
				<CryptoTable></CryptoTable>
			</main>
		</div>
	);
}
