import Head from "next/head";
import Image from "next/image";
import {
	accountObserver,
	makeAccount,
	removeUser,
	resetPassword,
	signInAccount,
	signOutAccount,
	updateEmailAddress,
	updateUserPassword,
	updateUserProfile,
	verifyEmail,
} from "../lib/pass_auth";

import { deleteUserData, readUserData, writeUserData } from "../lib/database";
import styles from "../styles/Home.module.css";
import { signInGoogle } from "../lib/google_auth";

const userID = "2";
const userName = "Wil";
const userEmail = "wilvandijkhuizen@gmail.com";
const userPass = "testing123";
const newPass = "dingdong";

export default function Home() {
	function handleDatabase() {
		console.log("Hey you clicked me");
		// writeUserData(userID, userName, userEmail);
		// console.log("STARTING TO DELETE");
		deleteUserData("1");
		readUserData();
	}

	function handleAuth() {
		// signInAccount(userEmail, userPass);
		signInGoogle();
		// removeUser();
		// accountObserver();
		// signOutAccount();
		// resetPassword(userEmail);
		// updateUserPassword(userPass);
		// accountObserver();
		// updateUserProfile();
		// accountObserver();
		// console.log("You made an account");
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<button onClick={handleDatabase}>Database Button</button>
				<div>
					<br></br>
				</div>
				<button onClick={handleAuth}>Authentication Button</button>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
